/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
import { type FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { BrandCard, BrandLogo, ImageBlock } from '@founder-os/ui'
import { MarketplaceShowcase } from './MarketplaceShowcase'

const capabilities = [
	['Local discovery', 'Find useful products and trusted businesses close to home.'],
	['Circular commerce', 'Keep quality goods moving through local communities.'],
	['Business visibility', 'Give independent businesses a clear local presence.'],
	['Simple operations', 'Connect listings, enquiries, customers, and follow-up.'],
]

function FoundThisBob({ open, onClose }: { open: boolean; onClose: () => void }) {
	const [question, setQuestion] = useState('')
	const [messages, setMessages] = useState([{ role: 'bob', text: 'Hi, I’m Bob AI. Ask me about finding goods, local businesses, or joining FoundThis.' }])
	if (!open) return null
	const submit = (event: FormEvent) => { event.preventDefault(); const text = question.trim(); if (!text) return; setMessages((items) => [...items, { role: 'visitor', text }, { role: 'bob', text: 'FoundThis helps people discover useful local goods and gives local businesses one place to manage listings and marketplace activity. Bob AI is the onboarding layer that helps people start, learn, and keep moving.' }]); setQuestion('') }
	return <section className="fixed inset-x-4 bottom-4 z-50 ml-auto max-w-sm overflow-hidden border border-[#E6D26A] bg-white shadow-2xl sm:right-6"><header className="flex items-center justify-between bg-[#FFD600] px-4 py-3 text-[#2E2E2E]"><strong>Bob AI</strong><button type="button" onClick={onClose} aria-label="Close Bob AI">×</button></header><div className="max-h-72 space-y-3 overflow-y-auto bg-[#FFFBE6] p-4">{messages.map((message, index) => <p key={`${message.role}-${index}`} className={`w-fit max-w-[88%] px-3 py-2 text-sm ${message.role === 'bob' ? 'bg-white' : 'ml-auto bg-[#FFF0A3]'}`}>{message.text}</p>)}</div><form onSubmit={submit} className="flex gap-2 border-t border-[#E6D26A] p-3"><input className="min-w-0 flex-1 border border-[#D6B800] px-3 py-2 text-sm" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask Bob about FoundThis" aria-label="Ask Bob AI"/><button className="bg-[#FFD600] px-4 text-[#2E2E2E]" type="submit">Send</button></form></section>
}

export const foundItPlans = [
	{ id: 'business', name: 'Data Operations', price: '£19.99', description: 'A complete marketplace presence for one local business with Bob AI onboarding support.', features: ['1 data operations console', 'Listings, enquiries and customer tools', 'Bob AI listing support', '1 staff account'], modules: ['Listings', 'Enquiries', 'Customers', 'Bob AI'], featured: false },
	{ id: 'premium', name: 'Intelligence', price: '£49.99', description: 'Coordinate a growing local marketplace network with Bob AI as the onboarding layer.', features: ['1 intelligence console', 'Up to 5 data operations consoles', 'Marketplace analytics', 'Advanced Bob AI tools', 'Up to 10 staff accounts'], modules: ['Network intelligence', 'Marketplace analytics', 'Staff', 'Intelligence'], featured: true },
	{ id: 'large', name: 'Large', price: '£99.99', description: 'Advanced discovery tools for larger networks with Bob AI onboarding and support.', features: ['1 management console', 'Up to 20 business consoles', 'Advanced analytics and automation', 'Priority onboarding and support', 'Up to 50 staff accounts'], modules: ['All management modules', 'Automation', 'Advanced analytics', 'Priority support'], featured: false },
] as const

const foundItLegal = [
	['Terms', 'FoundThis is available to approved marketplace participants for lawful local commerce and discovery. Account details, listings, and communications must remain accurate and responsible.'],
	['Privacy', 'FoundThis processes account, listing, enquiry, and marketplace activity data to provide tenant-scoped services, security, support, and analytics.'],
	['Cookies', 'Essential cookies and browser storage maintain secure sessions, preferences, and protected console access.'],
	['Refunds', 'Refund requests are reviewed against the active subscription period, enabled marketplace features, and completed onboarding work.'],
	['Data Operations Agreement', 'Data operations teams remain responsible for listing accuracy, fulfilment, customer communication, staff access, and applicable marketplace obligations.'],
	['Intelligence Agreement', 'Intelligence teams may oversee approved workspaces within package and privacy limits, without bypassing tenant access controls.'],
]

export function FoundThisSite() {
	const [bobOpen, setBobOpen] = useState(false)
	const [legalOpen, setLegalOpen] = useState<string | null>(null)
	const activeLegal = foundItLegal.find(([title]) => title === legalOpen)
	const consoleLinks = [
		{ label: 'Intelligence', href: 'http://localhost:4003/console' },
		{ label: 'Data Ops', href: 'http://localhost:4003/console' },
	]
	return <main className="min-h-screen bg-[#050816] text-[#e5eefc]">
		<header className="sticky top-0 z-30 border-b border-white/10 bg-[#0b1220]/85 backdrop-blur"><div className="mx-auto flex min-h-[72px] max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-3"><a href="#top" className="flex items-center gap-3"><BrandLogo brand="foundit" className="h-11 w-11"/><span><strong className="block text-xl text-white">FoundThis</strong><small className="text-slate-300">Marketplace OS</small></span></a><nav className="order-3 flex w-full items-center gap-4 overflow-x-auto text-sm font-semibold text-slate-200 md:order-none md:w-auto"><button type="button" onClick={() => { window.location.href = 'http://localhost:4000/console' }} className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">↩</span><span>Back to FoundingOS</span></button><a href="#why" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">◉</span><span>Why FoundThis</span></a><a href="#how" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">⌁</span><span>How it works</span></a><a href="#pricing" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">◆</span><span>Pricing</span></a><a href="#bob" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">✦</span><span>Bob AI</span></a></nav></div></header>
		<section id="top" className="relative overflow-hidden bg-[#17130a] text-white"><div className="absolute inset-0 bg-gradient-to-r from-[#17130a] via-[#111827]/80 to-[#facc15]/20"/><div className="relative mx-auto flex min-h-[76vh] max-w-6xl items-center px-5 py-16"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#fef3c7]">Marketplace OS</p><h1 className="mt-5 text-5xl font-bold leading-tight md:text-6xl">Find more of what matters, closer to home.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Connect communities, independent businesses, useful listings, enquiries, and marketplace operations in one clear discovery layer.</p>				<div className="mt-8 flex flex-wrap gap-3"><a href="#pricing" className="bg-[#facc15] px-6 py-3 font-semibold text-slate-950">Choose your package</a><button type="button" onClick={() => setBobOpen(true)} className="border border-white/60 bg-white/5 px-6 py-3 font-semibold text-[#facc15] backdrop-blur">Chat with Bob AI</button></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{consoleLinks.map(({ label, href }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left shadow-[0_12px_32px_rgba(0,0,0,.18)] backdrop-blur transition hover:-translate-y-0.5 hover:border-[#facc15]/50"><span className="block text-xs font-bold uppercase tracking-[.18em] text-[#fef3c7]">Open workspace</span><span className="mt-2 block text-lg font-bold text-white">{label}</span><span className="mt-2 block text-sm text-slate-300">{label === 'Intelligence' ? 'Marketplace intelligence workspace' : 'Business operations workspace'}</span></a>)}</div><p className="mt-3 text-sm text-slate-300">Pick the workspace that fits your team.</p><ImageBlock variant="foundit-dashboard" alt="FoundThis dashboard preview" caption="Marketplace workspace preview" glow="#facc15" className="mt-8" /></div></div></section>    <section id="why" className="bg-white py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#806B00]">Why FoundThis</p><h2 className="mt-3 max-w-3xl text-4xl font-bold">Local discovery designed around real communities.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{capabilities.map(([title, copy], index) => <BrandCard key={title} brand="foundit" title={title} description={copy} accent="#FFD600" className={`h-full ${index % 2 ? 'bg-[#FFFBE6]' : ''}`}><span className="text-3xl font-black text-[#806B00]">0{index + 1}</span></BrandCard>)}</div></div></section>
		<section id="how" className="border-y border-[#E6D26A] py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#806B00]">How it works</p><h2 className="mt-3 text-4xl font-bold">Build your marketplace presence in four steps.</h2><div className="mt-10 grid md:grid-cols-4">{[['1', 'Choose', 'Select the package for your marketplace footprint.'], ['2', 'Apply', 'Submit verified business and brand details.'], ['3', 'Publish', 'Configure listings, teams, locations, and discovery settings.'], ['4', 'Grow', 'Launch, answer enquiries, and improve with Bob AI.']].map(([step, title, copy]) => <article key={step} className="border-l-2 border-[#FFD600] px-5 py-3"><span className="text-sm font-bold text-[#806B00]">STEP {step}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6F6751]">{copy}</p></article>)}</div></div></section>
		<section id="bob" className="bg-[#FFD600] py-20"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-sm font-bold uppercase tracking-[.18em]">Bob AI powers your marketplace</p><h2 className="mt-3 text-4xl font-bold">Discovery, support, sales, and insight in one assistant.</h2><p className="mt-5 max-w-2xl text-lg leading-8">Bob helps visitors find the right route, businesses improve listings, managers forecast pipeline, and teams connect sales, marketing, social channels, and analytics.</p><div className="mt-7 flex flex-wrap gap-2">{['Visitor support', 'Listing tools', 'Sales insight', 'Marketing content', 'Social linking', 'Pipeline analytics'].map((item) => <span key={item} className="rounded-full border border-[#2E2E2E]/30 bg-white/40 px-4 py-2 text-sm font-semibold">{item}</span>)}</div><div className="mt-5 flex flex-wrap gap-2">{['WhatsApp', 'Telegram', 'Messenger', 'iMessage', 'SMS'].map((service) => <a key={service} href="/company/contact" className="inline-flex items-center gap-2 rounded-full border border-[#2E2E2E]/20 bg-white/60 px-4 py-2 text-sm font-semibold text-[#2E2E2E]"><span aria-hidden="true" className="text-base">✦</span>{service}</a>)}</div><button type="button" onClick={() => setBobOpen(true)} className="mt-8 bg-[#2E2E2E] px-8 py-4 text-lg font-bold text-white">Talk to Bob AI</button></div><button type="button" onClick={() => setBobOpen(true)} className="bob-ai-circle mx-auto grid aspect-square w-full max-w-[290px] place-items-center rounded-full bg-[#2E2E2E] text-white shadow-2xl"><span><strong className="block text-8xl">B</strong><span className="text-sm font-bold uppercase tracking-[.2em] text-[#FFD600]">Bob AI</span></span></button></div></section>
		<section className="bg-white py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#806B00]">Console previews</p><h2 className="mt-3 text-4xl font-bold">Marketplace work at the right level.</h2><div className="mt-10 grid gap-6 lg:grid-cols-2">{[['Data Operations Console', ['Live listings: 42', 'New enquiries: 18', 'Saved by customers: 126', 'Bob suggestion: refresh 5 listings']], ['Intelligence Console', ['Active businesses: 5', 'Staff seats: 8 of 10', 'Marketplace reach: 18,420', 'Bob forecast: enquiries up 16%']]].map(([title, rows]) => <article key={title as string} className="overflow-hidden border border-[#E6D26A] bg-[#2E2E2E] text-white shadow-xl"><ImageBlock variant="foundit-dashboard" alt={`${title as string} preview`} caption={`${title as string} preview`} glow="#facc15" /><header className="flex justify-between border-b border-white/10 px-5 py-4"><strong>{title as string}</strong><span className="bg-[#FFD600] px-3 py-1 text-xs font-bold text-[#2E2E2E]">LIVE</span></header><div className="grid gap-3 p-5 sm:grid-cols-2">{(rows as string[]).map((row) => <div key={row} className="bg-[#3A3A3A] p-4 text-sm">{row}</div>)}</div></article>)}</div></div></section>
		<section className="border-y border-[#E6D26A] py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#806B00]">Owner vs Merchant</p><h2 className="mt-3 text-4xl font-bold">Clear responsibility across the marketplace.</h2><div className="mt-9 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse bg-white text-left"><thead><tr><th className="border border-[#E6D26A] p-4">Capability</th><th className="border border-[#E6D26A] p-4">Merchant</th><th className="border border-[#E6D26A] p-4">Owner</th></tr></thead><tbody>{[['Listings and enquiries', 'Full access', 'Oversight'], ['Merchant spaces', '1 assigned', 'Up to package limit'], ['Staff', 'Own team', 'Network limits'], ['Analytics', 'Own performance', 'Marketplace performance'], ['Bob AI', 'Listing support', 'Forecasting and strategy']].map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell} className="border border-[#E6D26A] p-4 text-sm">{cell}</td>)}</tr>)}</tbody></table></div></div></section>
		<section id="pricing" className="bg-[#2E2E2E] py-20 text-white"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#FFD600]">Marketplace packages</p><h2 className="mt-3 text-4xl font-bold">Choose your discovery capacity.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{foundItPlans.map((plan) => <article key={plan.name} className={`flex flex-col border p-6 ${plan.featured ? 'border-[#FFD600] bg-[#3A3A3A]' : 'border-white/20 bg-[#353535]'}`}><h3 className="text-2xl font-bold">{plan.name}</h3><p className="mt-4"><strong className="text-4xl text-[#FFD600]">{plan.price}</strong><span>/month</span></p><p className="mt-3 min-h-12 text-sm text-white/70">{plan.description}</p><ul className="mt-6 flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className="text-sm"><span className="mr-2 text-[#FFD600]">✓</span>{feature}</li>)}</ul><Link to={`/foundit-site/packages/${plan.id}`} className="mt-7 bg-[#FFD600] px-4 py-3 text-center font-bold text-[#2E2E2E]">Start with {plan.name}</Link></article>)}</div></div></section>
		<MarketplaceShowcase/>
		<footer className="border-t border-[#E6D26A] bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 md:grid-cols-[1fr_2fr]"><div><strong className="text-xl">FoundThis</strong><p className="mt-2 text-sm text-[#6F6751]">Marketplace OS for local discovery.</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 md:justify-end">{foundItLegal.map(([title]) => <button type="button" key={title} onClick={() => setLegalOpen(title)} className="text-sm font-semibold">{title}</button>)}</div></div></footer>
		<button type="button" onClick={() => setBobOpen(true)} className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-[#FFD600] font-bold shadow-xl" aria-label="Open Bob AI">B</button><FoundThisBob open={bobOpen} onClose={() => setBobOpen(false)}/>
		{activeLegal && <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true"><article className="max-h-[85vh] w-full max-w-2xl overflow-y-auto bg-white p-7"><div className="flex justify-between"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#806B00]">FoundThis legal</p><h2 className="mt-2 text-3xl font-bold">{activeLegal[0]}</h2></div><button type="button" onClick={() => setLegalOpen(null)} className="text-3xl" aria-label="Close legal document">×</button></div><p className="mt-6 leading-7 text-[#6F6751]">{activeLegal[1]}</p><p className="mt-5 text-sm text-[#6F6751]">Subject to the complete agreement supplied during onboarding.</p></article></div>}
	</main>
}
