/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
'use client'

import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'

type Question = { id: string; prompt: string }
type Answer = { questionId: string; answer: string; autoGenerated?: boolean }
type SurveyShape = { id: string; title: string; questions: Question[] }

export function SurveyEngine({ survey, initialAnswers, moduleId }: { survey: SurveyShape; initialAnswers: Answer[]; moduleId: string }) {
  const router = useRouter()
  const answeredIds = useMemo(() => new Set(initialAnswers.filter((a) => !a.autoGenerated).map((a) => a.questionId)), [initialAnswers])
  const startIndex = useMemo(() => {
    const firstUnanswered = survey.questions.findIndex((question) => !answeredIds.has(question.id))
    return firstUnanswered === -1 ? survey.questions.length - 1 : firstUnanswered
  }, [survey.questions, answeredIds])

  const [index, setIndex] = useState(startIndex)
  const [draft, setDraft] = useState('')
  const [followUp, setFollowUp] = useState<Question | null>(null)
  const [followUpDraft, setFollowUpDraft] = useState('')
  const [saving, setSaving] = useState(false)
  const [savedAt, setSavedAt] = useState('')

  const question = survey.questions[index]
  const progress = Math.round((index / survey.questions.length) * 100)

  async function postAnswer(payload: { questionId: string; answer: string; autosave?: boolean }) {
    const response = await fetch('/api/tester/survey', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    })
    return response.json()
  }

  async function saveDraft() {
    if (!draft.trim()) return
    setSaving(true)
    await postAnswer({ questionId: question.id, answer: draft, autosave: true })
    setSaving(false)
    setSavedAt(new Date().toLocaleTimeString())
  }

  function advance(data: { done?: boolean; redirect?: string }) {
    if (data.done) {
      router.push(data.redirect ?? `/tester/demo/${moduleId}`)
      return
    }
    setDraft('')
    setIndex((current) => Math.min(current + 1, survey.questions.length - 1))
  }

  async function submitAnswer() {
    const data = await postAnswer({ questionId: question.id, answer: draft })
    if (data.followUp) {
      setFollowUp(data.followUp)
      return
    }
    advance(data)
  }

  async function submitFollowUp(skip: boolean) {
    if (!skip && followUpDraft.trim() && followUp) {
      const data = await postAnswer({ questionId: followUp.id, answer: followUpDraft })
      setFollowUp(null)
      setFollowUpDraft('')
      advance(data)
      return
    }
    setFollowUp(null)
    setFollowUpDraft('')
    advance({ done: index + 1 >= survey.questions.length })
  }

  return (
    <article className="panel fo-card">
      <div className="quantum-sync-meter" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}>
        <span style={{ width: `${progress}%` }} />
      </div>
      <p><small>Question {index + 1} of {survey.questions.length}</small></p>

      {followUp ? (
        <>
          <h2>Follow-up</h2>
          <p>{followUp.prompt}</p>
          <label className="manager-field">
            <span>Your answer (optional)</span>
            <textarea value={followUpDraft} onChange={(event) => setFollowUpDraft(event.target.value)} rows={3} />
          </label>
          <div className="tester-survey-actions">
            <button type="button" className="btn btn-secondary" onClick={() => submitFollowUp(true)}>Skip</button>
            <button type="button" className="btn btn-primary" onClick={() => submitFollowUp(false)}>Submit follow-up</button>
          </div>
        </>
      ) : (
        <>
          <h2>{question.prompt}</h2>
          <label className="manager-field">
            <span>Your answer</span>
            <textarea value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={saveDraft} rows={4} />
          </label>
          <p><small>{saving ? 'Saving…' : savedAt ? `Auto-saved ${savedAt}` : 'Answers auto-save as you type.'}</small></p>
          <div className="tester-survey-actions">
            <button type="button" className="btn btn-primary" disabled={!draft.trim()} onClick={submitAnswer}>
              {index + 1 === survey.questions.length ? 'Finish survey' : 'Next question'}
            </button>
          </div>
        </>
      )}
    </article>
  )
}
