/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { isSimplifiedRegion } from '@foundingos/config'

type SectionKind = 'module' | 'businessplan' | 'legal' | 'website' | 'console' | 'pos' | 'intelligence'
type Question = { id: string; prompt: string; section?: string; sectionKind?: SectionKind; target?: string }
type Answer = { questionId: string; answer: string; autoGenerated?: boolean }
type SurveyShape = { id: string; title: string; questions: Question[] }

const SECTION_ICON: Record<SectionKind, string> = {
  module: '▣', businessplan: '◈', legal: '⚖', website: '🌐', console: '🖥', pos: '🧾', intelligence: '🧠',
}

// Module-specific (a1, b1, ...) and business-plan (bp1, bp2, ...) questions don't carry an
// explicit section/sectionKind in the data — inferred here by ID prefix instead, so the module
// survey blocks in tester-data.ts never needed to be individually retrofitted.
function inferSection(question: Question): { label: string; kind: SectionKind } {
  if (question.section && question.sectionKind) return { label: question.section, kind: question.sectionKind }
  if (question.id.startsWith('bp')) return { label: 'Business Plan Understanding', kind: 'businessplan' }
  return { label: 'Your Module', kind: 'module' }
}

type SwitcherOption = { code: string; label: string; href: string; available: boolean; note?: string }

export function SurveyEngine({
  survey,
  initialAnswers,
  moduleId,
  freeRoamHref,
  completeNarratorLine,
  completeCelebrationLine,
  freeRoamEnteredLine,
  emotionalClosingLine,
  signatureMomentLine,
  freeRoamFirstStepLine,
  hasCompletedSurveyBefore,
  freeRoamInviteLines,
  freeRoamTips,
  sectionNarratorLines,
  pacingReassuranceLines,
  accessibilityReminderLines,
  targetJokes,
  missionNarratorLine,
  microBreakLines,
  switcherOptions,
  switcherTitle,
  switcherNarratorLine,
  freeRoamUnlockLine,
}: {
  survey: SurveyShape
  initialAnswers: Answer[]
  moduleId: string
  freeRoamHref: string
  completeNarratorLine: string
  completeCelebrationLine: string
  freeRoamEnteredLine: string
  emotionalClosingLine: string
  signatureMomentLine: string
  freeRoamFirstStepLine: string
  hasCompletedSurveyBefore: boolean
  freeRoamInviteLines: string[]
  freeRoamTips: string[]
  sectionNarratorLines: Record<SectionKind, string>
  pacingReassuranceLines: string[]
  accessibilityReminderLines: string[]
  targetJokes: Record<string, string>
  missionNarratorLine: string
  microBreakLines: string[]
  switcherOptions: SwitcherOption[]
  switcherTitle: string
  switcherNarratorLine: string
  freeRoamUnlockLine: string
}) {
  const answeredIds = useMemo(() => new Set(initialAnswers.filter((a) => !a.autoGenerated).map((a) => a.questionId)), [initialAnswers])
  const startIndex = useMemo(() => {
    const firstUnanswered = survey.questions.findIndex((question) => !answeredIds.has(question.id))
    return firstUnanswered === -1 ? survey.questions.length - 1 : firstUnanswered
  }, [survey.questions, answeredIds])

  const [index, setIndex] = useState(startIndex)
  const [draft, setDraft] = useState('')
  const [followUp, setFollowUp] = useState<Question | null>(null)
  const [followUpDraft, setFollowUpDraft] = useState('')
  const [saving, setSaving] = useState(false)
  const [savedAt, setSavedAt] = useState('')
  const [completed, setCompleted] = useState(false)
  // Real geo-based content simplification: detected once, client-side, via the visitor's real
  // navigator.language (through the shared @foundingos/config utility) — WhatsApp-style shorter
  // button labels for the regions this OS targets for simplified copy.
  const [simplified, setSimplified] = useState(false)
  useEffect(() => { setSimplified(isSimplifiedRegion()) }, [])
  // Switcher code box for the completion-state panel: real React state/handler (not the
  // shared no-file <script> pattern used elsewhere) because this panel only ever enters the
  // DOM after the client-side "completed" transition — a page-load script would never find it.
  const [switcherCode, setSwitcherCode] = useState('')
  const [switcherMessage, setSwitcherMessage] = useState('')
  function submitSwitcherCode(e: React.FormEvent) {
    e.preventDefault()
    const code = switcherCode.trim().toUpperCase()
    const option = switcherOptions.find((o) => o.code === code)
    if (!option) {
      setSwitcherMessage(code ? 'Code not recognized — try one from the list above.' : 'Type a code first (e.g. R1, M1, S1).')
      return
    }
    if (option.available) {
      window.location.href = option.href
      return
    }
    setSwitcherMessage(option.note || "That part of the OS isn't available for your current session.")
  }

  const question = survey.questions[index]
  const progress = Math.round((index / survey.questions.length) * 100)

  // Every distinct broad section, in the order it first appears, so we can show "Section X of
  // N" and detect exactly when we cross into a new one — computed once from the full question
  // list already available client-side.
  const sectionOrder = useMemo(() => {
    const seen: string[] = []
    for (const q of survey.questions) {
      const label = inferSection(q).label
      if (!seen.includes(label)) seen.push(label)
    }
    return seen
  }, [survey.questions])

  const current = inferSection(question)
  const previous = index > 0 ? inferSection(survey.questions[index - 1]) : null
  const isNewSection = current.label !== previous?.label
  const sectionIndex = sectionOrder.indexOf(current.label)
  const isNewTarget = Boolean(question.target) && question.target !== (index > 0 ? survey.questions[index - 1]?.target : undefined)

  async function postAnswer(payload: { questionId: string; answer: string; autosave?: boolean }) {
    const response = await fetch('/api/tester/survey', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      // moduleId is only ever used server-side for a real Super Founder Admin session (which
      // has no single assigned survey the way a real tester does) — harmless extra field for
      // every real tester/buyer/customer/investor session, which resolves via its own cookie.
      body: JSON.stringify({ ...payload, moduleId }),
    })
    return response.json()
  }

  async function saveDraft() {
    if (!draft.trim()) return
    setSaving(true)
    await postAnswer({ questionId: question.id, answer: draft, autosave: true })
    setSaving(false)
    setSavedAt(new Date().toLocaleTimeString())
  }

  function advance(data: { done?: boolean; redirect?: string }) {
    // Survey completion no longer navigates away — it shows the narrator's wrap-up and the
    // Quantum Free Roam invitation right here, in place, so that moment is never skipped.
    if (data.done) {
      setCompleted(true)
      return
    }
    setDraft('')
    setIndex((current) => Math.min(current + 1, survey.questions.length - 1))
  }

  async function submitAnswer() {
    const data = await postAnswer({ questionId: question.id, answer: draft })
    if (data.followUp) {
      setFollowUp(data.followUp)
      return
    }
    advance(data)
  }

  async function submitFollowUp(skip: boolean) {
    if (!skip && followUpDraft.trim() && followUp) {
      const data = await postAnswer({ questionId: followUp.id, answer: followUpDraft })
      setFollowUp(null)
      setFollowUpDraft('')
      advance(data)
      return
    }
    setFollowUp(null)
    setFollowUpDraft('')
    advance({ done: index + 1 >= survey.questions.length })
  }

  if (completed) {
    return (
      <div className="stack">
        <article className="panel fo-card quantum-frame">
          <h2>Survey complete</h2>
          <p>Thanks — your {survey.title.replace(/^Survey [A-Z—]*\s*—?\s*/, '') || 'survey'} answers are saved.</p>
        </article>
        {!hasCompletedSurveyBefore && (
          <article className="panel fo-card quantum-frame">
            <div className="quantum-narrator-panel">
              <p>{signatureMomentLine}</p>
            </div>
          </article>
        )}
        <div className="quantum-narrator-panel">
          <p>{freeRoamUnlockLine}</p>
          <p>{completeCelebrationLine}</p>
          <p>{completeNarratorLine}</p>
          <p>{freeRoamInviteLines[0]}</p>
          <p>{freeRoamInviteLines[1]} {freeRoamInviteLines[2]}</p>
          <p><small>{freeRoamTips.join(' ')}</small></p>
        </div>
        <Link href={freeRoamHref} className="quantum-freeroam-box">
          <strong>{simplified ? 'Explore Now' : 'Jump Into Free Roam — Explore the Quantum WhatsApp OS'}</strong>
          <small>{hasCompletedSurveyBefore ? freeRoamEnteredLine : freeRoamFirstStepLine} Read-only exploration of your unlocked module — nothing you click can break anything.</small>
        </Link>
        <div className="quantum-narrator-panel">
          <p>{emotionalClosingLine}</p>
        </div>

        <article className="panel fo-card quantum-frame">
          <div className="module-card-top"><span>🧭</span><strong>{switcherTitle}</strong></div>
          <div className="quantum-narrator-panel">
            <p>{switcherNarratorLine}</p>
          </div>
          <div style={{ display: 'grid', gap: 8 }}>
            {switcherOptions.map((option) => (
              option.available ? (
                <Link key={option.code} href={option.href} className="btn btn-secondary quantum-btn" style={{ width: '100%', justifyContent: 'flex-start' }}>{option.code} · {option.label}</Link>
              ) : (
                <div key={option.code} className="btn btn-secondary" style={{ width: '100%', justifyContent: 'flex-start', opacity: 0.5, cursor: 'default' }}>
                  {option.code} · {option.label} <small style={{ marginLeft: 6 }}>({option.note})</small>
                </div>
              )
            ))}
          </div>
          <form onSubmit={submitSwitcherCode} style={{ display: 'flex', flexDirection: 'column', gap: 10, marginTop: 12 }}>
            <div style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap' }}>
              <input
                type="text"
                value={switcherCode}
                onChange={(e) => setSwitcherCode(e.target.value)}
                placeholder="Enter a code (e.g. R1, M1, S1)"
                style={{ padding: '10px 14px', borderRadius: 999, border: '1px solid var(--line)', background: 'var(--surface)', color: 'var(--text)' }}
              />
              <button type="submit" className="btn btn-primary quantum-btn">Go</button>
            </div>
            {switcherMessage && <p><small>{switcherMessage}</small></p>}
          </form>
        </article>
      </div>
    )
  }

  return (
    <div className="stack">
      {index === 0 && (
        <div className="quantum-narrator-panel">
          <p>{missionNarratorLine}</p>
        </div>
      )}

      {isNewSection && sectionIndex > 0 && (
        <div className="quantum-narrator-panel">
          <p>{microBreakLines[(sectionIndex - 1) % microBreakLines.length]}</p>
        </div>
      )}

      {isNewSection && (
        <article className="panel fo-card quantum-frame">
          <div className="module-card-top">
            <span className="quantum-step-badge">Section {sectionIndex + 1} of {sectionOrder.length}</span>
            <strong>{SECTION_ICON[current.kind]} {current.label}</strong>
          </div>
          <div className="quantum-narrator-panel">
            <p>{sectionNarratorLines[current.kind]}</p>
            <p><small>{pacingReassuranceLines[sectionIndex % pacingReassuranceLines.length]}</small></p>
            {current.kind !== 'module' && current.kind !== 'businessplan' && (
              <p><small>{accessibilityReminderLines[sectionIndex % accessibilityReminderLines.length]}</small></p>
            )}
          </div>
        </article>
      )}

      {!isNewSection && isNewTarget && question.target && (
        <div className="quantum-narrator-panel">
          <p>Let's look at {question.target}.{targetJokes[question.target] ? ` ${targetJokes[question.target]}` : ''}</p>
        </div>
      )}

      <article className="panel fo-card">
        <div className="quantum-sync-meter" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}>
          <span style={{ width: `${progress}%` }} />
        </div>
        <p><small>Question {index + 1} of {survey.questions.length} · {current.label}{question.target ? ` · ${question.target}` : ''}</small></p>

        {followUp ? (
          <>
            <h2>Follow-up</h2>
            <p>{followUp.prompt}</p>
            <label className="manager-field">
              <span>Your answer (optional)</span>
              <textarea value={followUpDraft} onChange={(event) => setFollowUpDraft(event.target.value)} rows={3} />
            </label>
            <div className="tester-survey-actions">
              <button type="button" className="btn btn-secondary" onClick={() => submitFollowUp(true)}>Skip</button>
              <button type="button" className="btn btn-primary" onClick={() => submitFollowUp(false)}>Submit follow-up</button>
            </div>
          </>
        ) : (
          <>
            <h2>{question.prompt}</h2>
            <label className="manager-field">
              <span>Your answer</span>
              <textarea value={draft} onChange={(event) => setDraft(event.target.value)} onBlur={saveDraft} rows={4} />
            </label>
            <p><small>{saving ? 'Saving…' : savedAt ? `Auto-saved ${savedAt}` : 'Answers auto-save as you type.'}</small></p>
            <div className="tester-survey-actions">
              <button type="button" className="btn btn-primary" disabled={!draft.trim()} onClick={submitAnswer}>
                {simplified
                  ? (index + 1 === survey.questions.length ? 'Send' : 'Next')
                  : (index + 1 === survey.questions.length ? 'Finish survey' : 'Next question')}
              </button>
            </div>
          </>
        )}
      </article>
    </div>
  )
}
