/*
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/

// Realistic starting records so each module reads like the tool people expect.
// Format: "name|secondary|value". Missing modules fall back to generic seed data.
export const sampleText: Record<string, string[]> = {
  'retail/sales-pipeline': ['Office coffee contract|Harbour Cafe|£4,800', 'Wholesale bread supply|Willowbrook Bakery|£12,400', 'Corporate gifting|North & Co|£3,250', 'Event catering|Deacon & Rye|£6,900', 'Monthly deli restock|The Corner Deli|£2,150', 'Franchise pilot|Priya Anand|£18,000'],
  'retail/orders': ['#1042|Amina Yusuf · 3 items · WhatsApp|£86.40', '#1043|Harbour Cafe · 12 items · Wholesale|£412.00', '#1044|Sofia Martins · 1 item · Website|£24.99', '#1045|North & Co · 6 items · Instagram|£158.20', '#1046|Priya Anand · 2 items · In store|£41.50', '#1047|The Corner Deli · 20 items · Wholesale|£620.00'],
  'retail/point-of-sale': ['Sale #3301|2 × Flat white, 1 × Croissant|£9.00', 'Sale #3302|Sourdough loaf, Strawberry jam|£8.25', 'Sale #3303|Coffee beans 1kg|£18.00', 'Sale #3304|Gift hamper|£45.00', 'Sale #3305|3 × Croissant, Oat milk 1L|£9.90'],
  'retail/crm': ['Amina Yusuf|amina.yusuf@mail.com · 07700 900123|£1,240', 'Harbour Cafe|orders@harbourcafe.co.uk · Trade|£8,420', 'Sofia Martins|sofia.m@mail.com · 07700 900456|£312', 'North & Co|buying@northco.co.uk · Trade|£5,180', 'Priya Anand|priya.a@mail.com · 07700 900789|£960', 'The Corner Deli|hello@cornerdeli.co.uk · Trade|£3,640'],
  'retail/segments': ['Lapsed 60 days|No order in the last 60 days|214', 'VIP spenders|Lifetime value over £500|86', 'WhatsApp opted-in|Consented to WhatsApp updates|1120', 'New this month|First order in the last 30 days|63'],
  'retail/loyalty': ['Amina Yusuf|Gold · 50 pts to next reward|2450', 'Priya Anand|Silver · 120 pts to next reward|980', 'Sofia Martins|Bronze · 300 pts to next reward|420', 'Tom Hale|Gold · reward ready|3100', 'Grace Obi|Silver · 60 pts to next reward|1140'],
  'retail/products': ['Sourdough loaf|Bakery · BR-001|£4.50', 'Flat white|Coffee · CF-010|£3.20', 'Croissant|Bakery · BR-014|£2.60', 'Oat milk 1L|Grocery · GR-220|£2.10', 'Strawberry jam|Pantry · PN-031|£3.75', 'Coffee beans 1kg|Coffee · CF-100|£18.00', 'Granola 500g|Pantry · PN-044|£5.40', 'Gift hamper|Gifts · GF-001|£45.00'],
  'retail/inventory': ['Coffee beans 1kg|Bean Roasters Ltd · CF-100', 'Oat milk 1L|Dairy Alt Co · GR-220', 'Sourdough flour 16kg|Millstone Flour · BR-900', 'Takeaway cups 12oz|EcoPack Supplies · PK-012', 'Strawberry jam|Orchard Preserves · PN-031', 'Granola 500g|Hillside Granola · PN-044'],
  'retail/promotions': ['10% off first order|Code WELCOME10 · Website|£1,240', 'Coffee + pastry £4|In store · weekday mornings|£860', 'Free delivery over £30|Website & WhatsApp|£2,110', 'Double loyalty points|VIP segment|£640'],
  'retail/channels': ['Website|Online storefront|£8,420', 'WhatsApp|Orders via chat|£5,130', 'Instagram Shop|Social commerce|£2,210', 'In store|Point of sale|£12,860', 'Wholesale|Trade accounts|£6,400'],
  'retail/production-orders': ['Sourdough × 120|Bakery line · due 06:00|£540', 'Croissant × 200|Pastry line · due 05:30|£520', 'Granola × 60 bags|Kitchen · due Thu|£324', 'Gift hampers × 25|Packing bench · due Fri|£1,125'],
  'retail/boms': ['Sourdough loaf|Flour 500g, water, salt, starter|£0.82', 'Croissant|Flour, butter, sugar, yeast|£0.64', 'Gift hamper|Jam, granola, beans, box|£21.40', 'Granola 500g|Oats, honey, nuts, seeds|£1.95'],
  'retail/purchasing': ['PO-2201|Bean Roasters Ltd · 20 × Coffee beans 1kg|£260.00', 'PO-2202|Dairy Alt Co · 48 × Oat milk 1L|£67.20', 'PO-2203|Millstone Flour · 10 × 16kg sacks|£185.00', 'PO-2204|EcoPack Supplies · 2,000 cups|£140.00', 'PO-2205|Orchard Preserves · 36 jars|£72.00'],
  'retail/suppliers': ['Bean Roasters Ltd|Coffee · 3-day lead time|£4,200', 'Dairy Alt Co|Milk alternatives · next-day|£1,860', 'Millstone Flour|Flour · 5-day lead time|£2,940', 'EcoPack Supplies|Packaging · 7-day lead time|£1,120', 'Orchard Preserves|Pantry · 4-day lead time|£760'],
  'retail/fulfilment': ['#1039|Tracked 24 · 2 parcels · Amina Yusuf|£86.40', '#1040|Local courier · Harbour Cafe|£412.00', '#1041|Click & collect · Sofia Martins|£24.99', '#1038|Tracked 48 · North & Co|£158.20', '#1037|Local courier · The Corner Deli|£620.00'],
  'retail/returns': ['RMA-501|#1021 · Damaged in transit · Sofia Martins|£24.99', 'RMA-502|#1025 · Wrong size · Priya Anand|£41.50', 'RMA-503|#1030 · Changed mind · Tom Hale|£18.00', 'RMA-504|#1033 · Faulty · North & Co|£158.20'],
  'retail/service': ['Order arrived late|Sofia Martins · WhatsApp|High', 'Wrong item sent|North & Co · Email|High', 'Refund question|Priya Anand · Web chat|Medium', 'Allergen information|Harbour Cafe · Phone|Low', 'Change delivery address|Amina Yusuf · WhatsApp|Medium'],
  'retail/payments': ['PAY-7781|Card · #1042 Amina Yusuf|£86.40', 'PAY-7782|Bank transfer · #1043 Harbour Cafe|£412.00', 'PAY-7783|Mobile money · #1045 North & Co|£158.20', 'PAY-7784|Card · #1044 Sofia Martins|£24.99', 'PAY-7785|Cash · #1046 Priya Anand|£41.50'],
  campaigns: ['Summer menu launch|WhatsApp broadcast · 1,120 recipients|£640', 'Loyalty double points|Email · VIP segment|£220', 'Weekend brunch promo|Instagram ads|£480', 'Back to school bundles|SMS · Families segment|£310', 'Win back lapsed customers|WhatsApp · Lapsed 60 days|£150'],
  content: ['Seasonal menu reveal|Instagram carousel|Launch', 'Meet the baker|Short video|Brand', 'Wholesale price list|PDF · Trade|Sales', 'Customer of the month|Instagram story|Community'],
  'marketing/leads': ['Grace Obi|Downloaded wholesale price list|£2,400', 'Tom Hale|Asked about event catering|£1,800', 'Kofi Mensah|Instagram DM · office coffee|£3,600', 'Lena Fischer|Website form · franchise|£18,000', 'Omar Haddad|WhatsApp · gift hampers|£900'],
  'marketing/audiences': ['WhatsApp subscribers|Opted in via checkout|1120', 'Instagram followers|Social|4830', 'Email list|Newsletter sign-ups|2260', 'Trade buyers|Wholesale accounts|74'],
  'marketing/segments': ['High intent|Visited pricing twice this week|142', 'Cart abandoners|Left checkout in last 7 days|58', 'Local 5 miles|Within delivery radius|1640', 'Birthday this month|Date of birth on file|37'],
  'marketing/channels': ['WhatsApp|Broadcasts & replies|£5,130', 'Instagram|Organic & ads|£2,210', 'Email|Newsletter|£1,480', 'Google Ads|Search|£960'],
  'marketing/journeys': ['Welcome series|3 WhatsApp messages over 7 days|412', 'Abandoned cart|Reminder after 2 hours|58', 'Win-back|Offer after 60 days inactive|214', 'Post-purchase review|Ask for review after 3 days|380'],
  'marketing/brand-studio': ['Primary logo|SVG · approved|Brand', 'Colour palette|6 colours · approved|Brand', 'Menu template|Canva · draft|Print', 'Social templates|12 layouts|Social'],
  'finance/invoices': ['INV-1042|Harbour Cafe|£1,240.00', 'INV-1043|North & Co|£3,480.00', 'INV-1044|The Corner Deli|£620.00', 'INV-1045|Deacon & Rye|£2,150.00', 'INV-1046|Willowbrook Bakery|£4,900.00', 'INV-1047|Priya Anand|£310.00'],
  'finance/bills': ['Bean Roasters Ltd|Coffee beans · bill 88213|£620.00', 'Energy supplier|Electricity · March|£410.00', 'Landlord|Rent · Q2|£3,600.00', 'EcoPack Supplies|Packaging · bill 5521|£185.00', 'Millstone Flour|Flour · bill 1190|£370.00'],
  'finance/banking': ['Business current account|High-street bank ••4412|£18,240', 'Savings reserve|••9021|£25,000', 'Card settlements|Payment processor payouts|£2,140', 'Petty cash|Till float|£200'],
  'finance/reconciliation': ['Payout 14 Mar|Bank line · CARD PAYOUT|£1,284.50', 'Harbour Cafe payment|Bank line · HARBOUR CAFE LTD|£1,240.00', 'Rent Q2|Bank line · LANDLORD STO|£3,600.00', 'Unknown transfer|Bank line · REF 88213|£620.00', 'Energy direct debit|Bank line · DD ENERGY|£410.00'],
  'finance/expenses': ['Train to supplier visit|Travel · Amina Yusuf|£48.20', 'Client lunch|Meals · Tom Hale|£62.00', 'Market stall fee|Events · Priya Anand|£85.00', 'Card machine rolls|Supplies · Sofia Martins|£14.99', 'Van fuel|Travel · Kofi Mensah|£72.40'],
  'finance/payments': ['Supplier run — week 12|4 bills|£4,815.00', 'Payroll transfer|March staff pay|£11,420.00', 'HMRC VAT|Q1 return|£4,210.00', 'Card fees|Payment processor|£96.30'],
  'finance/budgets': ['Marketing|Q2 budget|£6,000', 'Stock purchasing|Q2 budget|£24,000', 'Staff|Q2 budget|£36,000', 'Equipment|Q2 budget|£4,000'],
  'finance/tax': ['VAT return Q1|Due 7 May · HMRC|£4,210.00', 'PAYE & NI March|Due 22 Apr · HMRC|£2,860.00', 'Corporation tax|FY 2025 · estimate|£8,900.00', 'Business rates|Council · instalment|£640.00'],
  'finance/approvals': ['New espresso machine|Capex · Tom Hale|£2,400', 'Extra weekend staff|Staffing · Priya Anand|£680', 'Instagram ad boost|Marketing · Sofia Martins|£300', 'Supplier switch|Contract · Amina Yusuf|£1,200'],
  'talent/candidates': ['Amara Okafor|Barista · via job board|£24,000', 'Daniel Price|Store manager · referral|£34,000', 'Mei Chen|Pastry chef · Instagram|£28,000', 'Lucas Silva|Delivery driver · WhatsApp|£23,000', 'Hannah Moore|Bookkeeper · LinkedIn|£30,000', 'Yusuf Ali|Barista · walk-in|£24,000'],
  'talent/jobs': ['Barista (full-time)|Harbour St store · 14 applicants|£24,000', 'Store manager|Harbour St store · 6 applicants|£34,000', 'Pastry chef|Central kitchen · 9 applicants|£28,000', 'Delivery driver|Logistics · 11 applicants|£23,000'],
  'talent/interviews': ['Amara Okafor|Barista · trial shift|Round 2', 'Daniel Price|Store manager · video call|Round 1', 'Mei Chen|Pastry chef · practical|Round 2', 'Hannah Moore|Bookkeeper · phone screen|Round 1'],
  'talent/offers': ['Mei Chen|Pastry chef · start 1 May|£28,000', 'Amara Okafor|Barista · start 22 Apr|£24,000', 'Lucas Silva|Delivery driver · start 29 Apr|£23,000'],
  'hr/onboarding': ['Mei Chen|Right to work, contract, uniform|Day 1', 'Amara Okafor|Food hygiene course, till training|Week 1', 'Lucas Silva|Licence check, van induction|Day 1', 'Grace Obi|Bank details, pension opt-in|Week 2'],
  'hr/people': ['Tom Hale|Store manager · Harbour St|Full-time', 'Priya Anand|Head baker · Central kitchen|Full-time', 'Sofia Martins|Barista · Harbour St|Part-time', 'Kofi Mensah|Driver · Logistics|Full-time', 'Grace Obi|Bookkeeper · Office|Part-time', 'Amina Yusuf|Operations lead · Office|Full-time'],
  'hr/performance': ['Tom Hale|Q1 review · store targets|92', 'Priya Anand|Q1 review · waste reduction|88', 'Sofia Martins|Q1 review · customer score|81', 'Kofi Mensah|Q1 review · on-time delivery|76'],
  'hr/time-off': ['Sofia Martins|Annual leave · 3 days · 14–16 May|3 days', 'Kofi Mensah|Sick leave · 1 day|1 day', 'Tom Hale|Annual leave · 1 week · June|5 days', 'Priya Anand|Training day|1 day'],
  'hr/learning': ['Food hygiene level 2|Required · 4 staff|4 enrolled', 'Allergen awareness|Required · 6 staff|6 enrolled', 'Till & refunds|Onboarding|2 enrolled', 'First aid at work|Optional|1 enrolled'],
  'hr/payroll': ['March payroll|12 staff · monthly|£11,420.00', 'March overtime|4 staff|£640.00', 'Holiday pay adjustment|2 staff|£310.00', 'April payroll|12 staff · monthly|£11,580.00'],
  'talent/talent-pool': ['Grace Obi|Bookkeeper · available now|£28,000', 'Leo Byrne|Chef de partie · 2 weeks notice|£30,000', 'Nadia Karim|Warehouse lead · temp-to-perm|£14/hr', 'Sam Otieno|Delivery driver · weekends|£13/hr'],
  'talent/clients': ['Harbour Cafe Group|Hospitality · 3 open roles|15%', 'North & Co Logistics|Warehousing · 5 open roles|£1,800', 'Willowbrook Bakery|Food production · 1 open role|12%'],
  'talent/placements': ['Leo Byrne|Harbour Cafe Group · chef|£4,500', 'Nadia Karim|North & Co · warehouse lead|£1,800', 'Grace Obi|Willowbrook · bookkeeper|£3,360'],
  'talent/references': ['Mei Chen|Former employer · Riverside Hotel|Positive', 'Amara Okafor|Character reference|Pending', 'Lucas Silva|DVLA licence check|Clear'],
  'hr/contracts': ['Mei Chen|Permanent · 40 hrs|£28,000', 'Amara Okafor|Permanent · 30 hrs|£24,000', 'Lucas Silva|Fixed term 6 months|£23,000', 'Sofia Martins|Part-time · 20 hrs|£12.60/hr'],
  'hr/rotas': ['Mon early|Sofia Martins · Harbour St|8', 'Mon late|Tom Hale · Harbour St|8', 'Tue bake|Priya Anand · Central kitchen|9', 'Sat delivery|Unassigned · Logistics|6'],
  'hr/timesheets': ['Sofia Martins|Week 14|22.5', 'Kofi Mensah|Week 14|41', 'Priya Anand|Week 14|45', 'Tom Hale|Week 14|40'],
  'hr/sickness': ['Kofi Mensah|Flu · 2–3 Apr|2', 'Sofia Martins|Migraine · 9 Apr|1', 'Priya Anand|Back injury · fit note|5'],
  'hr/right-to-work': ['Mei Chen|Share code check|2028-06-30', 'Lucas Silva|UK passport|No expiry', 'Amara Okafor|Visa · skilled worker|2027-01-15'],
  'hr/documents': ['Employment contract|Mei Chen|Contract', 'Food hygiene certificate|Amara Okafor|Certificate', 'Payslip consent|Lucas Silva|Form'],
  'hr/policies': ['Staff handbook 2026|Everyone|10/12', 'Holiday policy|Everyone|12/12', 'Lone working policy|Drivers|3/4', 'Allergen policy|Kitchen and front of house|8/9'],
  'hr/engagement': ['Pulse survey April|Response rate 83%|7.9', 'Harbour St team|Store team score|8.2', 'Central kitchen|Kitchen team score|7.1', 'Drivers|Logistics team score|6.8'],
  'logistics/dispatch': ['Load 14 · North|8 drops · Van 3 · Kofi Mensah|8 drops', 'Load 15 · City centre|12 drops · Van 1|12 drops', 'Load 16 · Coastal|5 drops · Van 2|5 drops', 'Load 17 · Wholesale|3 drops · Truck 1|3 drops'],
  'logistics/deliveries': ['DEL-3301|Harbour Cafe · 12 Quay St|£412.00', 'DEL-3302|North & Co · Unit 4, Mill Rd|£158.20', 'DEL-3303|Amina Yusuf · 8 Elm Close|£86.40', 'DEL-3304|The Corner Deli · 2 High St|£620.00', 'DEL-3305|Deacon & Rye · 19 Market Sq|£2,150.00'],
  'logistics/exceptions': ['Failed delivery — no access|DEL-3298 · Deacon & Rye|High', 'Damaged parcel|DEL-3290 · Sofia Martins|Medium', 'Van breakdown|Load 12 · Van 2|High', 'Address not found|DEL-3295 · Tom Hale|Low'],
  'logistics/routes': ['North loop|8 stops · 42 miles|2h 40m', 'City centre|12 stops · 18 miles|3h 10m', 'Coastal|5 stops · 55 miles|2h 05m', 'Wholesale run|3 stops · 30 miles|1h 30m'],
  'logistics/billing': ['LB-801|Harbour Cafe · March deliveries|£240.00', 'LB-802|North & Co · March deliveries|£180.00', 'LB-803|Deacon & Rye · pallet move|£420.00', 'LB-804|The Corner Deli · March deliveries|£96.00'],
  'logistics/quotes': ['Q-311|Weekly wholesale run · Deacon & Rye|£1,200.00', 'Q-312|Event delivery · North & Co|£340.00', 'Q-313|Pallet storage · Willowbrook Bakery|£860.00'],
  'health/triage': ['Chest discomfort|Patient J. Evans · phone|Urgent', 'Medication query|Patient A. Khan · web form|Routine', 'Rash follow-up|Patient L. Brown · photo|Soon', 'Repeat prescription|Patient M. Ito · app|Routine'],
  'health/follow-ups': ['J. Evans|Blood results review|2 days', 'L. Brown|Dermatology check|1 week', 'A. Khan|Medication review|2 weeks', 'R. Patel|Physio progress|1 week'],
  'health/compliance': ['Fire safety check|Annual · main clinic|Due', 'Data protection audit|Quarterly|Due', 'Controlled drugs register|Weekly|Due', 'Staff DBS renewals|3 staff|Due'],
  'health/billing': ['HB-201|J. Evans · consultation|£85.00', 'HB-202|L. Brown · follow-up|£55.00', 'HB-203|A. Khan · physio session|£60.00', 'HB-204|R. Patel · assessment|£120.00'],
  'health/claims': ['CL-901|J. Evans · insurer claim|£85.00', 'CL-902|R. Patel · insurer claim|£120.00', 'CL-903|M. Ito · insurer claim|£60.00'],
  'health/inventory': ['Nitrile gloves (box 100)|MedSupply Co · GL-100', 'Syringes 5ml|MedSupply Co · SY-005', 'Dressing packs|CarePlus · DR-020', 'Hand sanitiser 500ml|CarePlus · HS-500'],
  'intelligence/signals': ['Coffee beans will run out in 4 days|Retail · Inventory|High', 'Overdue invoices up 18% this week|Finance · Invoices|Medium', 'Weekend orders up 32%|Retail · Orders|Low', 'Driver on-time rate fell to 81%|Logistics · Deliveries|Medium', 'Two staff on leave during peak week|Workforce · Time off|Medium'],
  'intelligence/risks': ['Single supplier for coffee beans|Supply chain|High', 'Cash runway under 3 months if sales dip 20%|Finance|Medium', 'Key baker has no cover|Workforce|Medium', 'Card processor fees rising|Finance|Low'],
  'intelligence/anomalies': ['Refunds 3× normal on Tuesday|Retail · Returns|High', 'Energy bill 40% higher than usual|Finance · Bills|Medium', 'Unusual login location|Security|High', 'Order value drop on website|Retail · Orders|Low'],
  'intelligence/recommendations': ['Reorder 20 kg coffee beans now|Saves a stock-out on Friday|£260', 'Chase 3 overdue invoices by WhatsApp|Recovers cash this week|£6,250', 'Add a Saturday driver|Keeps on-time rate above 95%|£180', 'Run win-back offer to lapsed customers|214 customers · est. revenue|£1,900'],
}

export function moduleSamples(workspace: string, moduleId: string): Array<{ name: string; secondary: string; value?: string }> | undefined {
  const rows = sampleText[`${workspace}/${moduleId}`] ?? sampleText[moduleId]
  return rows?.map((row) => {
    const [name, secondary, value] = row.split('|')
    return { name, secondary, value }
  })
}
