/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
// Tester program state store. Import only from route handlers or server components (never
// edge middleware, never 'use client' files).
//
// Postgres/Prisma-backed (migrated off the local JSON file now that DATABASE_URL is
// configured) — this replaces the previous synchronous fs-based store, which crashed
// /api/tester/login in production with an ENOENT on mkdir (Vercel's filesystem is
// read-only outside /tmp). Dormant-safe: if DATABASE_URL isn't set, reads return an empty
// map and writes silently no-op, matching every other backend integration point in this
// ecosystem. All functions are now async (Prisma is always async) — every caller was
// updated to await them.
import { getPrismaClient } from '@foundingos/db'
import type { BrandSignal } from '@foundingos/config/brandSignalFeed'

export type TesterStatus = 'registered' | 'demo-viewed' | 'in-progress' | 'complete'
export type TesterAnswer = { questionId: string; answer: string; autoGenerated?: boolean }
export type SurveyRun = { id: string; answers: TesterAnswer[]; completedAt: string; signal?: BrandSignal }
export type TesterRecord = {
  id: string
  email: string
  moduleId: string
  moduleLabel: string
  surveyId: string
  status: TesterStatus
  currentAnswers: TesterAnswer[]
  runs: SurveyRun[]
  // The literal password or access code used at the most recent login — lets the tester
  // program track which credential (of any batch) was actually used, alongside the
  // email/module/timestamp fields this record already carries.
  lastCredentialUsed: string | null
  createdAt: string
  updatedAt: string
}

function toRecord(row: {
  id: string
  email: string
  moduleId: string
  moduleLabel: string
  surveyId: string
  status: string
  currentAnswers: unknown
  runs: unknown
  lastCredentialUsed: string | null
  createdAt: Date
  updatedAt: Date
}): TesterRecord {
  return {
    id: row.id,
    email: row.email,
    moduleId: row.moduleId,
    moduleLabel: row.moduleLabel,
    surveyId: row.surveyId,
    status: row.status as TesterStatus,
    currentAnswers: Array.isArray(row.currentAnswers) ? (row.currentAnswers as TesterAnswer[]) : [],
    runs: Array.isArray(row.runs) ? (row.runs as SurveyRun[]) : [],
    lastCredentialUsed: row.lastCredentialUsed ?? null,
    createdAt: row.createdAt.toISOString(),
    updatedAt: row.updatedAt.toISOString(),
  }
}

export async function readTesters(): Promise<Record<string, TesterRecord>> {
  const prisma = getPrismaClient()
  if (!prisma) return {} // Demo Mode — no DB configured.

  const rows = await prisma.testerSession.findMany()
  return Object.fromEntries(rows.map((row) => [row.id, toRecord(row)]))
}

export async function getTester(id: string): Promise<TesterRecord | null> {
  const prisma = getPrismaClient()
  if (!prisma) return null // Demo Mode — no DB configured.

  const row = await prisma.testerSession.findUnique({ where: { id } })
  return row ? toRecord(row) : null
}

export async function upsertTester(id: string, patch: Partial<TesterRecord>): Promise<TesterRecord> {
  const prisma = getPrismaClient()
  const existing = await getTester(id)
  const now = new Date()
  const next: TesterRecord = {
    id,
    email: patch.email ?? existing?.email ?? '',
    moduleId: patch.moduleId ?? existing?.moduleId ?? '',
    moduleLabel: patch.moduleLabel ?? existing?.moduleLabel ?? '',
    surveyId: patch.surveyId ?? existing?.surveyId ?? '',
    status: patch.status ?? existing?.status ?? 'registered',
    currentAnswers: patch.currentAnswers ?? existing?.currentAnswers ?? [],
    runs: patch.runs ?? existing?.runs ?? [],
    lastCredentialUsed: patch.lastCredentialUsed ?? existing?.lastCredentialUsed ?? null,
    createdAt: existing?.createdAt ?? now.toISOString(),
    updatedAt: now.toISOString(),
  }

  if (!prisma) return next // Demo Mode — nothing persisted, but the caller still gets a valid record for this request.

  await prisma.testerSession.upsert({
    where: { id },
    create: {
      id,
      email: next.email,
      moduleId: next.moduleId,
      moduleLabel: next.moduleLabel,
      surveyId: next.surveyId,
      status: next.status,
      currentAnswers: next.currentAnswers,
      runs: next.runs,
      lastCredentialUsed: next.lastCredentialUsed,
    },
    update: {
      email: next.email,
      moduleId: next.moduleId,
      moduleLabel: next.moduleLabel,
      surveyId: next.surveyId,
      status: next.status,
      currentAnswers: next.currentAnswers,
      runs: next.runs,
      lastCredentialUsed: next.lastCredentialUsed,
    },
  })
  return next
}
