/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
// Node-only JSON store for tester program state. Import only from route handlers
// or server components (never edge middleware, never 'use client' files).
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { BrandSignal } from '@foundingos/config/brandSignalFeed'

export type TesterStatus = 'registered' | 'in-progress' | 'complete'
export type TesterAnswer = { questionId: string; answer: string; autoGenerated?: boolean }
export type SurveyRun = { id: string; answers: TesterAnswer[]; completedAt: string; signal?: BrandSignal }
export type TesterRecord = {
  id: string
  email: string
  moduleId: string
  moduleLabel: string
  surveyId: string
  status: TesterStatus
  currentAnswers: TesterAnswer[]
  runs: SurveyRun[]
  createdAt: string
  updatedAt: string
}

const dataDir = join(dirname(fileURLToPath(import.meta.url)), 'data')
const dataFile = join(dataDir, 'testers.json')

function ensureFile() {
  if (!existsSync(dataDir)) mkdirSync(dataDir, { recursive: true })
  if (!existsSync(dataFile)) writeFileSync(dataFile, '{}', 'utf8')
}

export function readTesters(): Record<string, TesterRecord> {
  ensureFile()
  return JSON.parse(readFileSync(dataFile, 'utf8'))
}

export function writeTesters(testers: Record<string, TesterRecord>) {
  ensureFile()
  writeFileSync(dataFile, JSON.stringify(testers, null, 2), 'utf8')
}

export function getTester(id: string): TesterRecord | null {
  return readTesters()[id] ?? null
}

export function upsertTester(id: string, patch: Partial<TesterRecord>): TesterRecord {
  const all = readTesters()
  const existing = all[id]
  const now = new Date().toISOString()
  const next: TesterRecord = {
    id,
    email: patch.email ?? existing?.email ?? '',
    moduleId: patch.moduleId ?? existing?.moduleId ?? '',
    moduleLabel: patch.moduleLabel ?? existing?.moduleLabel ?? '',
    surveyId: patch.surveyId ?? existing?.surveyId ?? '',
    status: patch.status ?? existing?.status ?? 'registered',
    currentAnswers: patch.currentAnswers ?? existing?.currentAnswers ?? [],
    runs: patch.runs ?? existing?.runs ?? [],
    createdAt: existing?.createdAt ?? now,
    updatedAt: now,
  }
  all[id] = next
  writeTesters(all)
  return next
}
