/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
import { type FormEvent, useState } from 'react'
import { Link } from 'react-router-dom'
import { BrandCard, BrandLogo, ImageBlock } from '@founder-os/ui'

const capabilities = [
	['Trusted sourcing', 'Connect buyers with dependable local meat suppliers.'],
	['Fresh availability', 'Make current products and availability easier to discover.'],
	['Trade relationships', 'Keep enquiries, customers, orders, and follow-up connected.'],
	['Clear operations', 'Give suppliers and buyers one focused operating view.'],
]

function FoundMeatBob({ open, onClose }: { open: boolean; onClose: () => void }) {
	const [question, setQuestion] = useState('')
	const [messages, setMessages] = useState([{ role: 'bob', text: 'Hi, I’m Bob AI. Ask me about FoundMeat suppliers, products, or trade access.' }])
	if (!open) return null
	const submit = (event: FormEvent) => { event.preventDefault(); const text = question.trim(); if (!text) return; setMessages((items) => [...items, { role: 'visitor', text }, { role: 'bob', text: 'FoundMeat connects trusted suppliers, fresh availability, customer enquiries, and trade workflows. Bob AI is the onboarding layer that helps you start, train, and route work across your workspace.' }]); setQuestion('') }
	return <section className="fixed inset-x-4 bottom-4 z-50 ml-auto max-w-sm overflow-hidden border border-[#D6B5E8] bg-white shadow-2xl sm:right-6"><header className="flex items-center justify-between bg-[#B00020] px-4 py-3 text-white"><strong>Bob AI</strong><button type="button" onClick={onClose} aria-label="Close Bob AI">×</button></header><div className="max-h-72 space-y-3 overflow-y-auto bg-[#FFF4EB] p-4">{messages.map((message, index) => <p key={`${message.role}-${index}`} className={`w-fit max-w-[88%] px-3 py-2 text-sm ${message.role === 'bob' ? 'bg-white' : 'ml-auto bg-[#E9D1F5]'}`}>{message.text}</p>)}</div><form onSubmit={submit} className="flex gap-2 border-t border-[#E6D1D9] p-3"><input className="min-w-0 flex-1 border border-[#C8A6D9] px-3 py-2 text-sm" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Ask Bob about FoundMeat" aria-label="Ask Bob AI"/><button className="bg-[#B00020] px-4 text-white" type="submit">Send</button></form></section>
}

export const foundMeatPlans = [
	{ id: 'buyer', name: 'Meat Buyer', price: '£19.99', description: 'A focused trade workspace for one artisan butcher.', features: ['1 buyer console', 'Products, orders and customer tools', 'Bob AI trade support', '1 staff account'], modules: ['Products', 'Stock', 'Orders', 'Customers'], featured: false },
	{ id: 'supplier', name: 'Meat Supplier', price: '£49.99', description: 'Coordinate a trusted supplier and buyer network with Bob AI onboarding support.', features: ['1 supplier console', 'Up to 5 buyer consoles', 'Network and stock analytics', 'Advanced Bob AI tools', 'Up to 10 staff accounts'], modules: ['Supplier network', 'Stock analytics', 'Staff', 'Bob AI'], featured: true },
	{ id: 'large', name: 'Large', price: '£99.99', description: 'Advanced capacity for larger food operations with Bob AI as the universal onboarding layer.', features: ['1 management console', 'Up to 20 trade consoles', 'Advanced analytics and automation', 'Priority onboarding and support', 'Up to 50 staff accounts'], modules: ['All management modules', 'Automation', 'Advanced analytics', 'Priority support'], featured: false },
] as const

const foundMeatLegal = [
	['Terms', 'FoundMeat is available to approved artisan food businesses for lawful trade. Product, provenance, availability, and account information must remain accurate.'],
	['Privacy', 'FoundMeat processes account, supplier, product, order, and operational data to provide tenant-scoped services, security, support, and analytics.'],
	['Cookies', 'Essential cookies and browser storage maintain secure sessions, preferences, and protected console access.'],
	['Refunds', 'Refund requests are reviewed against the active subscription period, enabled features, and completed onboarding work.'],
	['Meat Buyer Agreement', 'Buyers remain responsible for product accuracy, food compliance, fulfilment, customer communication, and staff access.'],
	['Meat Supplier Agreement', 'Suppliers may oversee approved workspaces within package, privacy, and food-trade compliance limits without bypassing tenant controls.'],
]

export function FoundMeatSite() {
	const [bobOpen, setBobOpen] = useState(false)
	const [legalOpen, setLegalOpen] = useState<string | null>(null)
	const activeLegal = foundMeatLegal.find(([title]) => title === legalOpen)
	const consoleLinks = [
		{ label: 'Supplier', href: 'http://localhost:4002/console' },
		{ label: 'Logistics', href: 'http://localhost:4002/console' },
	]
	return <main className="min-h-screen bg-[#050816] text-[#e5eefc]">
		<header className="sticky top-0 z-30 border-b border-white/10 bg-[#0b1220]/85 backdrop-blur"><div className="mx-auto flex min-h-[72px] max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-3"><a href="#top" className="flex items-center gap-3"><BrandLogo brand="foundmeat" className="h-11 w-11"/><span><strong className="block text-xl text-white">FoundMeat</strong><small className="text-slate-300">Artisan Butcher OS</small></span></a><nav className="order-3 flex w-full items-center gap-4 overflow-x-auto text-sm font-semibold text-slate-200 md:order-none md:w-auto"><button type="button" onClick={() => { window.location.href = 'http://localhost:4000/console' }} className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">↩</span><span>Back to FoundingOS</span></button><a href="#why" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">◉</span><span>Why FoundMeat</span></a><a href="#how" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">⌁</span><span>How it works</span></a><a href="#pricing" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">◆</span><span>Pricing</span></a><a href="#bob" className="nav-chip"><span aria-hidden="true" className="nav-chip-icon">✦</span><span>Bob AI</span></a></nav></div></header>
		<section id="top" className="relative overflow-hidden bg-[#150b14] text-white"><div className="absolute inset-0 bg-gradient-to-r from-[#150b14] via-[#1f2937]/80 to-[#fb7185]/20"/><div className="relative mx-auto flex min-h-[76vh] max-w-6xl items-center px-5 py-16"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#fda4af]">Artisan Butcher OS</p><h1 className="mt-5 text-5xl font-bold leading-tight md:text-6xl">Trusted supply. Fresh opportunity.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Connect artisan butchers, trusted suppliers, fresh availability, customers, orders, and trade operations in one focused system.</p>						<div className="mt-8 flex flex-wrap gap-3"><a href="#pricing" className="bg-[#fb7185] px-6 py-3 font-semibold text-slate-950">Choose your package</a><button type="button" onClick={() => setBobOpen(true)} className="border border-white/60 bg-white/5 px-6 py-3 font-semibold text-[#fb7185] backdrop-blur">Chat with Bob AI</button></div><div className="mt-8 grid gap-4 sm:grid-cols-2">{consoleLinks.map(({ label, href }) => <a key={label} href={href} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-white/10 bg-white/5 p-4 text-left shadow-[0_12px_32px_rgba(0,0,0,.18)] backdrop-blur transition hover:-translate-y-0.5 hover:border-[#fb7185]/50"><span className="block text-xs font-bold uppercase tracking-[.18em] text-[#fda4af]">Open workspace</span><span className="mt-2 block text-lg font-bold text-white">{label}</span><span className="mt-2 block text-sm text-slate-300">{label === 'Supplier' ? 'Supplier oversight workspace' : 'Logistics coordination workspace'}</span></a>)}</div><p className="mt-3 text-sm text-slate-300">Pick the workspace that fits your team.</p><ImageBlock variant="foundmeat-dashboard" alt="FoundMeat dashboard preview" caption="Butcher workspace preview" glow="#fb7185" className="mt-8" /></div></div></section>		<section id="why" className="bg-white py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#B00020]">Why FoundMeat</p><h2 className="mt-3 max-w-3xl text-4xl font-bold">Purpose-built operations for trusted artisan food trade.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{capabilities.map(([title, copy], index) => <BrandCard key={title} brand="foundmeat" title={title} description={copy} accent="#B00020" className="h-full"><div className="h-1 w-12 bg-[#C62828]"/><span className="mt-5 block text-3xl font-black text-[#B00020]">0{index + 1}</span></BrandCard>)}</div></div></section>
		<section id="how" className="border-y border-[#E6D1D9] py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#B00020]">How it works</p><h2 className="mt-3 text-4xl font-bold">Bring trusted trade online in four steps.</h2><div className="mt-10 grid md:grid-cols-4">{[['1', 'Choose', 'Select capacity for your butcher or supplier network.'], ['2', 'Verify', 'Submit business, provenance, and brand details.'], ['3', 'Configure', 'Prepare products, availability, teams, and trade settings.'], ['4', 'Trade', 'Launch, serve customers, and improve with Bob AI.']].map(([step, title, copy]) => <article key={step} className="border-l-2 border-[#C62828] px-5 py-3"><span className="text-sm font-bold text-[#B00020]">STEP {step}</span><h3 className="mt-3 text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#765B6D]">{copy}</p></article>)}</div></div></section>
		<section id="bob" className="bg-[#B00020] py-20 text-white"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 lg:grid-cols-[.75fr_1.25fr]"><button type="button" onClick={() => setBobOpen(true)} className="bob-ai-circle mx-auto grid aspect-square w-full max-w-[290px] place-items-center rounded-full bg-[#C62828] shadow-2xl"><span><strong className="block text-8xl">B</strong><span className="text-sm font-bold uppercase tracking-[.2em]">Bob AI</span></span></button><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#F2C6FF]">Bob AI powers your trade</p><h2 className="mt-3 text-4xl font-bold">Support, sales, marketing, and insight for artisan operators.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[#F0DDF7]">Bob helps visitors understand the marketplace, supports product and order workflows, connects social channels, creates campaigns, and forecasts sales and stock signals.</p><div className="mt-7 flex flex-wrap gap-2">{['Customer support', 'Product tools', 'Sales insight', 'Marketing studio', 'Social linking', 'Stock analytics'].map((item) => <span key={item} className="rounded-full border border-white/30 px-4 py-2 text-sm font-semibold">{item}</span>)}</div><div className="mt-5 flex flex-wrap gap-2">{['WhatsApp', 'Telegram', 'Messenger', 'iMessage', 'SMS'].map((service) => <a key={service} href="/company/contact" className="inline-flex items-center gap-2 rounded-full border border-white/30 bg-white/10 px-4 py-2 text-sm font-semibold"><span aria-hidden="true" className="text-base">✦</span>{service}</a>)}</div>		<button type="button" onClick={() => setBobOpen(true)} className="mt-8 bg-white px-8 py-4 text-lg font-bold text-[#B00020]">Talk to Bob AI</button></div></div></section>
		<section className="bg-white py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#B00020]">Console previews</p><h2 className="mt-3 text-4xl font-bold">Fresh operational context at every level.</h2><div className="mt-10 grid gap-6 lg:grid-cols-2">{[['Buyer Console', ['Products available: 38', 'Orders to prepare: 12', 'Stock alerts: 4', 'Bob suggestion: promote weekend boxes']], ['Supplier Console', ['Active buyers: 5', 'Staff seats: 8 of 10', 'Network sales: £31,460', 'Bob forecast: demand up 11%']]].map(([title, rows]) => <article key={title as string} className="overflow-hidden border border-[#D6B5E8] bg-[#351A3C] text-white shadow-xl"><ImageBlock variant="foundmeat-dashboard" alt={`${title as string} preview`} caption={`${title as string} preview`} glow="#fb7185" /><header className="flex justify-between border-b border-white/10 px-5 py-4"><strong>{title as string}</strong><span className="bg-[#C62828] px-3 py-1 text-xs font-bold">LIVE</span></header><div className="grid gap-3 p-5 sm:grid-cols-2">{(rows as string[]).map((row) => <div key={row} className="bg-[#B00020] p-4 text-sm">{row}</div>)}</div></article>)}</div></div></section>
		<section className="border-y border-[#E6D1D9] py-20"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#B00020]">Buyer vs Supplier</p><h2 className="mt-3 text-4xl font-bold">Clear access across every trade relationship.</h2><div className="mt-9 overflow-x-auto"><table className="w-full min-w-[680px] border-collapse bg-white text-left"><thead><tr><th className="border border-[#E6D1D9] p-4">Capability</th><th className="border border-[#E6D1D9] p-4">Buyer</th><th className="border border-[#E6D1D9] p-4">Supplier</th></tr></thead><tbody>{[['Products and orders', 'Full access', 'Oversight'], ['Buyer spaces', '1 assigned', 'Up to package limit'], ['Staff', 'Own team', 'Network limits'], ['Analytics', 'Own trade performance', 'Network performance'], ['Bob AI', 'Daily support', 'Forecasting and strategy']].map((row) => <tr key={row[0]}>{row.map((cell) => <td key={cell} className="border border-[#E6D1D9] p-4 text-sm">{cell}</td>)}</tr>)}</tbody></table></div></div></section>
		<section id="pricing" className="bg-[#351A3C] py-20 text-white"><div className="mx-auto max-w-6xl px-5"><p className="text-sm font-bold uppercase tracking-[.18em] text-[#F2C6FF]">Artisan packages</p><h2 className="mt-3 text-4xl font-bold">Choose your trade capacity.</h2><div className="mt-10 grid gap-5 lg:grid-cols-3">{foundMeatPlans.map((plan) => <article key={plan.name} className={`flex flex-col border p-6 ${plan.featured ? 'border-[#C62828] bg-[#B00020]' : 'border-white/20 bg-[#421B4C]'}`}><h3 className="text-2xl font-bold">{plan.name}</h3><p className="mt-4"><strong className="text-4xl text-[#F2C6FF]">{plan.price}</strong><span>/month</span></p><p className="mt-3 min-h-12 text-sm text-white/70">{plan.description}</p><ul className="mt-6 flex-1 space-y-3">{plan.features.map((feature) => <li key={feature} className="text-sm"><span className="mr-2 text-[#F2C6FF]">✓</span>{feature}</li>)}</ul><Link to={`/foundmeat-site/packages/${plan.id}`} className="mt-7 bg-[#C62828] px-4 py-3 text-center font-bold">Start with {plan.name}</Link></article>)}</div></div></section>
		<footer className="border-t border-[#E6D1D9] bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-10 md:grid-cols-[1fr_2fr]"><div><strong className="text-xl">FoundMeat</strong><p className="mt-2 text-sm text-[#765B6D]">Artisan Butcher OS for trusted food commerce.</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 md:justify-end">{foundMeatLegal.map(([title]) => <button type="button" key={title} onClick={() => setLegalOpen(title)} className="text-sm font-semibold text-[#B00020]">{title}</button>)}</div></div></footer>
		<button type="button" onClick={() => setBobOpen(true)} className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-[#B00020] font-bold text-white shadow-xl" aria-label="Open Bob AI">B</button><FoundMeatBob open={bobOpen} onClose={() => setBobOpen(false)}/>
		{activeLegal && <div className="fixed inset-0 z-50 grid place-items-center bg-[#351A3C]/80 p-4" role="dialog" aria-modal="true"><article className="max-h-[85vh] w-full max-w-2xl overflow-y-auto bg-white p-7"><div className="flex justify-between"><div><p className="text-sm font-bold uppercase tracking-[.18em] text-[#B00020]">FoundMeat legal</p><h2 className="mt-2 text-3xl font-bold">{activeLegal[0]}</h2></div><button type="button" onClick={() => setLegalOpen(null)} className="text-3xl" aria-label="Close legal document">×</button></div><p className="mt-6 leading-7 text-[#765B6D]">{activeLegal[1]}</p><p className="mt-5 text-sm text-[#765B6D]">Subject to the complete agreement supplied during onboarding.</p></article></div>}
	</main>
}
