/* 
  © 2024–2026 FoundingOS. All rights reserved.
  Unauthorized copying, distribution, or modification is strictly prohibited.
*/
import { type FormEvent, useEffect, useState } from 'react'
import { Card, FunnelChart, HeatMap, InsightPanel, Table } from './index'
import { ClientDateTime } from './client-date'

export interface ScrapingClient { request<T>(path: string, init?: RequestInit): Promise<T> }
type Category = { category: string; configured: number; active: number }
type Run = { id: string; status: string; discovered: number; ingested: number; leadsPushed: number; errors?: Array<{ url: string; message: string }>; startedAt: string; source: { name: string; category: string; url: string } }
type Source = { id: string; name: string; category: string; url: string; active: boolean; intervalMinutes: number; maxItemsPerRun: number; lastRunAt?: string; lastSuccessAt?: string; lastError?: string; consecutiveFailures: number; runs: Run[] }
type Status = { enabled: boolean; running: boolean; categories: Category[]; sources: Source[]; recentRuns: Run[]; metrics: { sources: number; activeSources: number; items: number; failedRuns: number; pendingLeads: number } }
const empty: Status = { enabled: false, running: false, categories: [], sources: [], recentRuns: [], metrics: { sources: 0, activeSources: 0, items: 0, failedRuns: 0, pendingLeads: 0 } }
const labels: Record<string,string> = { 'free-items': 'Free item listings', 'marketplace-free': 'Marketplace free sections', 'community-free': 'Community free listings', 'merchant-free-offers': 'Merchant free offers', 'classifieds-free': 'Classifieds free sections' }

export function ScrapingControl({ client, tenantId, founder = false }: { client: ScrapingClient; tenantId?: string; founder?: boolean }) {
  const [data,setData]=useState<Status>(empty);const [message,setMessage]=useState('')
  const load=async()=>{try{const response=await client.request<{success:true;data?:Status}>('/status');if(!response.data?.metrics||!response.data.categories)throw new Error('Scraping analytics unavailable');setData(response.data);setMessage('')}catch(error){setData(empty);setMessage(error instanceof Error?error.message:'Scraping status unavailable')}}
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),30_000);return()=>window.clearInterval(timer)},[])
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;const value=new FormData(form);try{await client.request('/sources',{method:'POST',body:JSON.stringify({name:value.get('name'),category:value.get('category'),url:value.get('url'),tenantId,intervalMinutes:Number(value.get('intervalMinutes')),maxItemsPerRun:Number(value.get('maxItemsPerRun')),itemSelector:value.get('itemSelector'),linkSelector:value.get('linkSelector'),companyName:value.get('companyName'),merchantName:value.get('merchantName'),listingFeePence:Number(value.get('listingFeePence')),placementFeePence:Number(value.get('placementFeePence')),deliveryFeePence:Number(value.get('deliveryFeePence')),premiumFeePence:Number(value.get('premiumFeePence'))})});form.reset();await load()}catch(error){setMessage(error instanceof Error?error.message:'Unable to add source')}}
  const command=async(path:string,init:RequestInit={})=>{try{await client.request(path,{method:'POST',...init});await load()}catch(error){setMessage(error instanceof Error?error.message:'Scraping command failed')}}
  const toggle=async(source:Source)=>{try{await client.request(`/sources/${source.id}`,{method:'PATCH',body:JSON.stringify({active:!source.active})});await load()}catch(error){setMessage(error instanceof Error?error.message:'Unable to update source')}}
  const remove=async(source:Source)=>{if(!confirm(`Delete ${source.name}?`))return;try{await client.request(`/sources/${source.id}`,{method:'DELETE'});await load()}catch(error){setMessage(error instanceof Error?error.message:'Unable to delete source')}}
  return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-4"><InsightPanel title="Active sources" value={String(data.metrics.activeSources)} detail={`Scheduler ${data.enabled?(data.running?'running':'active'):'disabled'}`} tone={data.enabled?'positive':'warning'}/><InsightPanel title="Items ingested" value={String(data.metrics.items)}/><InsightPanel title="Failed runs" value={String(data.metrics.failedRuns)} tone={data.metrics.failedRuns?'warning':'default'}/><InsightPanel title="Pending leads" value={String(data.metrics.pendingLeads)} tone={data.metrics.pendingLeads?'warning':'default'}/></div>{message&&<p role="alert" className="border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</p>}
  <Card title="Source coverage"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{data.categories.map(item=><article key={item.category} className="border border-[var(--line)] p-3"><strong className="text-sm">{labels[item.category]||item.category}</strong><p className="mt-2 text-xs text-[var(--muted)]">{item.active} active · {item.configured} configured</p></article>)}</div></Card><div className="grid gap-5 lg:grid-cols-2"><Card title="Intelligence ingestion funnel"><FunnelChart data={[{label:'Active sources',value:data.metrics.activeSources},{label:'Items ingested',value:data.metrics.items},{label:'Leads pushed',value:data.recentRuns.reduce((sum,run)=>sum+run.leadsPushed,0)},{label:'Ready leads',value:Math.max(0,data.metrics.items-data.metrics.pendingLeads)}]}/></Card><Card title="Merchant source hotspots"><HeatMap data={data.categories.map(item=>({label:labels[item.category]||item.category,value:item.active}))}/></Card></div>
  <Card title="Add approved scraping source"><form onSubmit={submit} className="grid gap-3 md:grid-cols-4"><input name="name" required placeholder="Source name" className="border px-3 py-2"/><select name="category" required className="border px-3 py-2">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input name="url" type="url" required placeholder="Approved HTTPS source URL" className="border px-3 py-2 md:col-span-2"/><input name="companyName" required placeholder="Detected company override" className="border px-3 py-2"/><input name="merchantName" placeholder="Merchant contact name" className="border px-3 py-2"/><input name="itemSelector" placeholder="Item CSS selector (optional)" className="border px-3 py-2"/><input name="linkSelector" placeholder="Link CSS selector (optional)" className="border px-3 py-2"/><input name="intervalMinutes" type="number" min="5" defaultValue="60" placeholder="Interval minutes" className="border px-3 py-2"/><input name="maxItemsPerRun" type="number" min="1" max="100" defaultValue="20" placeholder="Max items" className="border px-3 py-2"/><input name="listingFeePence" type="number" min="0" placeholder="Listing fee pence" className="border px-3 py-2"/><input name="placementFeePence" type="number" min="0" placeholder="Priority fee pence" className="border px-3 py-2"/><input name="deliveryFeePence" type="number" min="0" placeholder="Delivery fee pence" className="border px-3 py-2"/><input name="premiumFeePence" type="number" min="0" placeholder="Premium fee pence" className="border px-3 py-2"/><button disabled={founder&&!tenantId} className="bg-[var(--console-accent,var(--primary))] px-4 py-2 font-semibold text-white disabled:opacity-50 md:col-span-2">Validate and activate source</button>{founder&&!tenantId&&<p className="text-sm text-[var(--muted)] md:col-span-2">Select a company before adding a source.</p>}</form></Card>
  <Card title="Active source registry"><Table headers={['Source','Category','Schedule','Last result','Actions']}><>{data.sources.map(source=><tr key={source.id}><td className="px-4 py-3"><strong>{source.name}</strong><a href={source.url} target="_blank" rel="noreferrer" className="block max-w-xs truncate text-xs text-[var(--muted)]">{source.url}</a></td><td className="px-4 py-3">{labels[source.category]||source.category}</td><td className="px-4 py-3">Every {source.intervalMinutes} min</td><td className="px-4 py-3 text-sm">{source.lastError?<span className="text-red-700">{source.lastError}</span>:source.lastSuccessAt?<><span>Success </span><ClientDateTime value={source.lastSuccessAt} /></>:'Not run'}</td><td className="px-4 py-3"><button onClick={()=>void command(`/sources/${source.id}/run`)} className="mr-2 border px-2 py-1 text-xs">Run now</button><button onClick={()=>void toggle(source)} className="mr-2 border px-2 py-1 text-xs">{source.active?'Pause':'Activate'}</button><button onClick={()=>void remove(source)} className="text-xs text-red-700">Delete</button></td></tr>)}</></Table>{founder&&<button onClick={()=>void command('/run-due')} className="mt-4 bg-[var(--console-accent,var(--primary))] px-4 py-2 text-sm font-semibold text-white">Run all due sources</button>}</Card>
  <Card title="Ingestion and error log"><Table headers={['Started','Source','Status','Discovered','Ingested','Leads','Errors']}><>{data.recentRuns.map(run=><tr key={run.id}><td className="px-4 py-3 text-sm"><ClientDateTime value={run.startedAt} /></td><td className="px-4 py-3 font-semibold">{run.source.name}</td><td className="px-4 py-3">{run.status}</td><td className="px-4 py-3">{run.discovered}</td><td className="px-4 py-3">{run.ingested}</td><td className="px-4 py-3">{run.leadsPushed}</td><td className="px-4 py-3 text-sm text-red-700">{run.errors?.map(error=>error.message).join('; ')||'—'}</td></tr>)}</></Table></Card></div>
}
